export const handycontrolSidebar = [
{
    text: 'HandyControl',
    collapsed: true,
    items: [
    {
        text: 'Attach', collapsed: true, items: [
        { text: 'BackgroundSwitchElement', link: '/handycontrol/attach/backgroundSwitchElement/index' },
        { text: 'BorderElement', link: '/handycontrol/attach/borderElement/index' },
        { text: 'BrushAttach', link: '/handycontrol/attach/brushAttach/index' },
        { text: 'DataGridAttach', link: '/handycontrol/attach/dataGridAttach/index' },
        { text: 'DropDownElement', link: '/handycontrol/attach/dropDownElement/index' },
        { text: 'EdgeElement', link: '/handycontrol/attach/edgeElement/index' },
        { text: 'GlobalShortcut', link: '/handycontrol/attach/globalShortcut/index' },
        { text: 'GridAttach', link: '/handycontrol/attach/gridAttach/index' },
        { text: 'GridViewAttach', link: '/handycontrol/attach/gridViewAttach/index' },
        { text: 'IconElement', link: '/handycontrol/attach/iconElement/index' },
        { text: 'IconSwitchElement', link: '/handycontrol/attach/iconSwitchElement/index' },
        { text: 'ImageAttach', link: '/handycontrol/attach/imageAttach/index' },
        { text: 'InfoElement', link: '/handycontrol/attach/infoElement/index' },
        { text: 'LinkElement', link: '/handycontrol/attach/linkElement/index' },
        { text: 'ListBoxAttach', link: '/handycontrol/attach/listboxAttach/index' },
        { text: 'MenuAttach', link: '/handycontrol/attach/menuAttach/index' },
        { text: 'MenuTopLineAttach', link: '/handycontrol/attach/menuTopLineAttach/index' },
        { text: 'PanelElement', link: '/handycontrol/attach/panelElement/index' },
        { text: 'PasswordBoxAttach', link: '/handycontrol/attach/passwordBoxAttach/index' },
        { text: 'RectangleAttach', link: '/handycontrol/attach/rectangleAttach/index' },
        { text: 'ScrollViewerAttach', link: '/handycontrol/attach/scrollViewerAttach/index' },
        { text: 'SelectAllButtonAttach', link: '/handycontrol/attach/selectAllButtonAttach/index' },
        { text: 'StatusSwitchElement', link: '/handycontrol/attach/statusSwitchElement/index' },
        { text: 'TextBlockAttach', link: '/handycontrol/attach/textBlockAttach/index' },
        { text: 'TipElement', link: '/handycontrol/attach/tipElement/index' },
        { text: 'TitleElement', link: '/handycontrol/attach/titleElement/index' },
        { text: 'ToggleButtonAttach', link: '/handycontrol/attach/toggleButtonAttach/index' },
        { text: 'VisualElement', link: '/handycontrol/attach/visualElement/index' },
        { text: 'WindowAttach', link: '/handycontrol/attach/windowAttach/index' },
    ]
    },
    {
    text: 'Basic_xaml', collapsed: true, items: [
        { text: 'Basic xaml definition', link: '/handycontrol/basic_xaml/index' },
        { text: 'Behavior', link: '/handycontrol/basic_xaml/behaviors/index' },
        { text: 'Brush', link: '/handycontrol/basic_xaml/brushes/index' },
        { text: 'Color', link: '/handycontrol/basic_xaml/colors/index' },
        { text: 'Converter', link: '/handycontrol/basic_xaml/converters/index' },
        { text: 'Effect', link: '/handycontrol/basic_xaml/effects/index' },
        { text: 'Font Size', link: '/handycontrol/basic_xaml/fonts/index' },
        { text: 'Geometric shape', link: '/handycontrol/basic_xaml/geometries/index' },
        { text: 'Path', link: '/handycontrol/basic_xaml/paths/index' },
        { text: 'Size', link: '/handycontrol/basic_xaml/sizes/index' },
    ]
    },
    {
    text: 'Breaking_changes', collapsed: true, items: [
        { text: 'Breaking Changes', link: '/handycontrol/breaking_changes/index' },
    ]
    },
    {
    text: 'Data', collapsed: true, items: [
        { text: 'Args', link: '/handycontrol/data/Args/index' },
        { text: 'Data', link: '/handycontrol/data/index' },
        { text: 'Enum', link: '/handycontrol/data/Enum/index' },
        { text: 'Flex', link: '/handycontrol/data/Flex/index' },
        { text: 'Gif', link: '/handycontrol/data/Gif/index' },
        { text: 'GlowWindow', link: '/handycontrol/data/GlowWindow/index' },
        { text: 'Info', link: '/handycontrol/data/Info/index' },
        { text: 'Operation', link: '/handycontrol/data/Operation/index' },
        { text: 'Range', link: '/handycontrol/data/Range/index' },
    ]
    },
    {
    text: 'Expression', collapsed: true, items: [
        { text: 'Drawing', link: '/handycontrol/expression/Drawing/index' },
        { text: 'Expression', link: '/handycontrol/expression/index' },
        { text: 'Media', link: '/handycontrol/expression/Media/index' },
        { text: 'Shapes', link: '/handycontrol/expression/Shapes/index' },
    ]
    },
    {
    text: 'Extend_controls', collapsed: true, items: [
        { text: 'AnimationPath', link: '/handycontrol/extend_controls/animationPath/index' },
        { text: 'AutoCompleteTextBox', link: '/handycontrol/extend_controls/autoCompleteTextBox/index' },
        { text: 'Badge', link: '/handycontrol/extend_controls/badge/index' },
        { text: 'BlurWindow', link: '/handycontrol/extend_controls/blurWindow/index' },
        { text: 'ButtonGroup', link: '/handycontrol/extend_controls/buttonGroup/index' },
        { text: 'CalendarWithClock', link: '/handycontrol/extend_controls/calendarWithClock/index' },
        { text: 'Card', link: '/handycontrol/extend_controls/card/index' },
        { text: 'Carousel', link: '/handycontrol/extend_controls/carousel/index' },
        { text: 'ChatBubble', link: '/handycontrol/extend_controls/chatBubble/index' },
        { text: 'CheckComboBox', link: '/handycontrol/extend_controls/checkComboBox/index' },
        { text: 'CirclePanel', link: '/handycontrol/extend_controls/circlePanel/index' },
        { text: 'CircleProgressBar', link: '/handycontrol/extend_controls/circleProgressBar/index' },
        { text: 'ClipGrid', link: '/handycontrol/extend_controls/clipGrid/index' },
        { text: 'Clock', link: '/handycontrol/extend_controls/clock/index' },
        { text: 'ColorPicker', link: '/handycontrol/extend_controls/colorPicker/index' },
        { text: 'ComboBox', link: '/handycontrol/extend_controls/comboBox/index' },
        { text: 'CompareSlider', link: '/handycontrol/extend_controls/compareSlider/index' },
        { text: 'ConfettiCannon', link: '/handycontrol/extend_controls/confettiCannon/index' },
        { text: 'ContextMenuButton', link: '/handycontrol/extend_controls/contextMenuButton/index' },
        { text: 'CoverFlow', link: '/handycontrol/extend_controls/coverFlow/index' },
        { text: 'CoverView', link: '/handycontrol/extend_controls/coverView/index' },
        { text: 'DashBorder', link: '/handycontrol/extend_controls/dashBorder/index' },
        { text: 'DatePicker', link: '/handycontrol/extend_controls/datePicker/index' },
        { text: 'DateTimePicker', link: '/handycontrol/extend_controls/dateTimePicker/index' },
        { text: 'Dialog', link: '/handycontrol/extend_controls/dialog/index' },
        { text: 'Divider', link: '/handycontrol/extend_controls/divider/index' },
        { text: 'Drawer', link: '/handycontrol/extend_controls/drawer/index' },
        { text: 'Effect', link: '/handycontrol/extend_controls/effect/index' },
        { text: 'ElementGroup', link: '/handycontrol/extend_controls/elementGroup/index' },
        { text: 'Empty', link: '/handycontrol/extend_controls/empty/index' },
        { text: 'Extended Control', link: '/handycontrol/extend_controls/index' },
        { text: 'FlexPanel', link: '/handycontrol/extend_controls/flexPanel/index' },
        { text: 'FlipClock', link: '/handycontrol/extend_controls/flipClock/index' },
        { text: 'FloatingBlock', link: '/handycontrol/extend_controls/floatingBlock/index' },
        { text: 'GifImage', link: '/handycontrol/extend_controls/gifImage/index' },
        { text: 'GlowWindow', link: '/handycontrol/extend_controls/glowWindow/index' },
        { text: 'GotoTop', link: '/handycontrol/extend_controls/gotoTop/index' },
        { text: 'Gravatar', link: '/handycontrol/extend_controls/gravatar/index' },
        { text: 'Grid', link: '/handycontrol/extend_controls/grid/index' },
        { text: 'Growl Information notification', link: '/handycontrol/extend_controls/growl/index' },
        { text: 'HatchBrushGenerator', link: '/handycontrol/extend_controls/hatchBrushGenerator/index' },
        { text: 'HighlightTextBlock', link: '/handycontrol/extend_controls/highlightTextBlock/index' },
        { text: 'HoneycombPanel', link: '/handycontrol/extend_controls/honeycombPanel/index' },
        { text: 'ImageBlock', link: '/handycontrol/extend_controls/imageBlock/index' },
        { text: 'ImageBrowser', link: '/handycontrol/extend_controls/imageBrowser/index' },
        { text: 'ImageSelector', link: '/handycontrol/extend_controls/imageSelector/index' },
        { text: 'ImageViewer', link: '/handycontrol/extend_controls/imageViewer/index' },
        { text: 'Loading', link: '/handycontrol/extend_controls/loading/index' },
        { text: 'Magnifier', link: '/handycontrol/extend_controls/magnifier/index' },
        { text: 'MessageBox', link: '/handycontrol/extend_controls/messageBox/index' },
        { text: 'MorphingAnimation', link: '/handycontrol/extend_controls/morphingAnimation/index' },
        { text: 'Notification', link: '/handycontrol/extend_controls/notification/index' },
        { text: 'NotifyIcon', link: '/handycontrol/extend_controls/notifyIcon/index' },
        { text: 'NumericUpDown', link: '/handycontrol/extend_controls/numericUpDown/index' },
        { text: 'OutlineText', link: '/handycontrol/extend_controls/outlineText/index' },
        { text: 'Pagination', link: '/handycontrol/extend_controls/pagination/index' },
        { text: 'PasswordBox', link: '/handycontrol/extend_controls/passwordBox/index' },
        { text: 'PinBox', link: '/handycontrol/extend_controls/pinBox/index' },
        { text: 'PopTip', link: '/handycontrol/extend_controls/popTip/index' },
        { text: 'PopupWindow', link: '/handycontrol/extend_controls/popupWindow/index' },
        { text: 'PreviewSlider', link: '/handycontrol/extend_controls/previewSlider/index' },
        { text: 'ProgressButton', link: '/handycontrol/extend_controls/progressButton/index' },
        { text: 'PropertyGrid', link: '/handycontrol/extend_controls/propertyGrid/index' },
        { text: 'RangeSlider', link: '/handycontrol/extend_controls/rangeSlider/index' },
        { text: 'Rate', link: '/handycontrol/extend_controls/rate/index' },
        { text: 'RelativePanel', link: '/handycontrol/extend_controls/relativePanel/index' },
        { text: 'Ribbon', link: '/handycontrol/extend_controls/ribbon/index' },
        { text: 'RunningBlock', link: '/handycontrol/extend_controls/runningBlock/index' },
        { text: 'ScreenShot', link: '/handycontrol/extend_controls/screenshot/index' },
        { text: 'ScrollViewer', link: '/handycontrol/extend_controls/scrollViewer/index' },
        { text: 'SearchBar', link: '/handycontrol/extend_controls/searchBar/index' },
        { text: 'Shield', link: '/handycontrol/extend_controls/shield/index' },
        { text: 'SideMenu', link: '/handycontrol/extend_controls/sideMenu/index' },
        { text: 'SimpleItemsControl', link: '/handycontrol/extend_controls/simpleItemsControl/index' },
        { text: 'SimplePanel', link: '/handycontrol/extend_controls/simplePanel/index' },
        { text: 'SimpleStackPanel', link: '/handycontrol/extend_controls/simpleStackPanel/index' },
        { text: 'SimpleText', link: '/handycontrol/extend_controls/simpleText/index' },
        { text: 'SplitButton', link: '/handycontrol/extend_controls/splitButton/index' },
        { text: 'Sprite', link: '/handycontrol/extend_controls/sprite/index' },
        { text: 'StepBar', link: '/handycontrol/extend_controls/stepBar/index' },
        { text: 'TabControl', link: '/handycontrol/extend_controls/tabControl/index' },
        { text: 'Tag', link: '/handycontrol/extend_controls/tag/index' },
        { text: 'TextBox', link: '/handycontrol/extend_controls/textBox/index' },
        { text: 'TimeBar', link: '/handycontrol/extend_controls/timeBar/index' },
        { text: 'TimePicker', link: '/handycontrol/extend_controls/timePicker/index' },
        { text: 'ToggleBlock', link: '/handycontrol/extend_controls/toggleBlock/index' },
        { text: 'Transfer', link: '/handycontrol/extend_controls/transfer/index' },
        { text: 'TransitioningContentControl', link: '/handycontrol/extend_controls/transitioningContentControl/index' },
        { text: 'UniformSpacingPanel', link: '/handycontrol/extend_controls/uniformSpacingPanel/index' },
        { text: 'WaterfallPanel', link: '/handycontrol/extend_controls/waterfallPanel/index' },
        { text: 'Watermark', link: '/handycontrol/extend_controls/watermark/index' },
        { text: 'WaveProgressBar', link: '/handycontrol/extend_controls/waveProgressBar/index' },
        { text: 'Window', link: '/handycontrol/extend_controls/window/index' },
    ]
    },
    {
    text: 'Index.md', collapsed: true, items: [
        { text: 'Welcome to HandyControl', link: '/handycontrol/index' },
    ]
    },
    {
    text: 'Intellisense', collapsed: true, items: [
        { text: 'Intellisense', link: '/handycontrol/intellisense/index' },
    ]
    },
    {
    text: 'Interactivity', collapsed: true, items: [
        { text: 'Behaviors', link: '/handycontrol/interactivity/behaviors/index' },
        { text: 'Commands', link: '/handycontrol/interactivity/commands/index' },
        { text: 'Hooks', link: '/handycontrol/interactivity/hooks/index' },
        { text: 'Interactivity', link: '/handycontrol/interactivity/index' },
        { text: 'Triggers', link: '/handycontrol/interactivity/triggers/index' },
    ]
    },
    {
    text: 'Langs', collapsed: true, items: [
        { text: 'Globalization', link: '/handycontrol/langs/index' },
    ]
    },
    {
    text: 'Media', collapsed: true, items: [
        { text: 'Animation', link: '/handycontrol/media/Animation/index' },
        { text: 'Effects', link: '/handycontrol/media/Effects/index' },
        { text: 'Media', link: '/handycontrol/media/index' },
    ]
    },
    {
    text: 'Native_controls', collapsed: true, items: [
        { text: 'Border', link: '/handycontrol/native_controls/border/index' },
        { text: 'Button', link: '/handycontrol/native_controls/button/index' },
        { text: 'Calendar', link: '/handycontrol/native_controls/calendar/index' },
        { text: 'CheckBox', link: '/handycontrol/native_controls/checkBox/index' },
        { text: 'ComboBox', link: '/handycontrol/native_controls/comboBox/index' },
        { text: 'ContentControl', link: '/handycontrol/native_controls/contentControl/index' },
        { text: 'ContextMenu', link: '/handycontrol/native_controls/contextMenu/index' },
        { text: 'DataGrid', link: '/handycontrol/native_controls/dataGrid/index' },
        { text: 'DatePicker', link: '/handycontrol/native_controls/datePicker/index' },
        { text: 'Expander', link: '/handycontrol/native_controls/expander/index' },
        { text: 'FlowDocument', link: '/handycontrol/native_controls/flowDocument/index' },
        { text: 'Frame', link: '/handycontrol/native_controls/frame/index' },
        { text: 'GroupBox', link: '/handycontrol/native_controls/groupBox/index' },
        { text: 'Image', link: '/handycontrol/native_controls/image/index' },
        { text: 'Label', link: '/handycontrol/native_controls/label/index' },
        { text: 'ListBox', link: '/handycontrol/native_controls/listBox/index' },
        { text: 'ListView', link: '/handycontrol/native_controls/listView/index' },
        { text: 'Menu', link: '/handycontrol/native_controls/menu/index' },
        { text: 'Native Control', link: '/handycontrol/native_controls/index' },
        { text: 'NavigationWindow', link: '/handycontrol/native_controls/navigationWindow/index' },
        { text: 'PasswordBox', link: '/handycontrol/native_controls/passwordBox/index' },
        { text: 'ProgressBar', link: '/handycontrol/native_controls/progressBar/index' },
        { text: 'RadioButton', link: '/handycontrol/native_controls/radioButton/index' },
        { text: 'RepeatButton', link: '/handycontrol/native_controls/repeatButton/index' },
        { text: 'RichTextBox', link: '/handycontrol/native_controls/richTextBox/index' },
        { text: 'ScrollViewer', link: '/handycontrol/native_controls/scrollViewer/index' },
        { text: 'Separator', link: '/handycontrol/native_controls/separator/index' },
        { text: 'Slider', link: '/handycontrol/native_controls/slider/index' },
        { text: 'StatusBar', link: '/handycontrol/native_controls/statusBar/index' },
        { text: 'TabControl', link: '/handycontrol/native_controls/tabControl/index' },
        { text: 'TextBlock', link: '/handycontrol/native_controls/textBlock/index' },
        { text: 'TextBox', link: '/handycontrol/native_controls/textBox/index' },
        { text: 'ToggleButton', link: '/handycontrol/native_controls/toggleButton/index' },
        { text: 'Toolbar', link: '/handycontrol/native_controls/toolBar/index' },
        { text: 'ToolTip', link: '/handycontrol/native_controls/toolTip/index' },
        { text: 'TreeView', link: '/handycontrol/native_controls/treeView/index' },
        { text: 'Window', link: '/handycontrol/native_controls/window/index' },
    ]
    },
    {
    text: 'PersianToolkit', collapsed: true, items: [
        { text: 'BindablePropertyBase', link: '/handycontrol/persianToolkit/bindablePropertyBase/index' },
        { text: 'BindingProxy', link: '/handycontrol/persianToolkit/bindingProxy/index' },
        { text: 'BindToEnum', link: '/handycontrol/persianToolkit/bindToEnum/index' },
        { text: 'BusyIndicator', link: '/handycontrol/persianToolkit/busyIndicator/index' },
        { text: 'CheckTreeView', link: '/handycontrol/persianToolkit/checkTreeView/index' },
        { text: 'ColorBrightnessExtension', link: '/handycontrol/persianToolkit/colorBrightnessExtension/index' },
        { text: 'Command', link: '/handycontrol/persianToolkit/command/index' },
        { text: 'Dynamic Language', link: '/handycontrol/persianToolkit/dynamicLanguage/index' },
        { text: 'Extensions', link: '/handycontrol/persianToolkit/extensions/index' },
        { text: 'Helpers', link: '/handycontrol/persianToolkit/helpers/index' },
        { text: 'IfExtension', link: '/handycontrol/persianToolkit/markupIfExtension/index' },
        { text: 'LoadingIndicator', link: '/handycontrol/persianToolkit/loadingIndicator/index' },
        { text: 'Logger', link: '/handycontrol/persianToolkit/logger/index' },
        { text: 'OptimizedObservableCollection', link: '/handycontrol/persianToolkit/optimizedObservableCollection/index' },
        { text: 'PersianCalendar', link: '/handycontrol/persianToolkit/persianCalendar/index' },
        { text: 'PersianCalendarWithClock', link: '/handycontrol/persianToolkit/persianCalendarWithClock/index' },
        { text: 'PersianDatePicker', link: '/handycontrol/persianToolkit/persianDatePicker/index' },
        { text: 'PersianDateTime', link: '/handycontrol/persianToolkit/persianDateTime/index' },
        { text: 'PersianDateTimePicker', link: '/handycontrol/persianToolkit/persianDateTimePicker/index' },
        { text: 'PersianToolkit', link: '/handycontrol/persianToolkit/index' },
        { text: 'SpeedoMeter', link: '/handycontrol/persianToolkit/speedoMeter/index' },
        { text: 'SplashWindow', link: '/handycontrol/persianToolkit/splashWindow/index' },
        { text: 'ThreadSafeObservableCollection', link: '/handycontrol/persianToolkit/threadSafeObservableCollection/index' },
        { text: 'UndoRedoObservableCollection', link: '/handycontrol/persianToolkit/undoRedoObservableCollection/index' },
        { text: 'Updatable Markup Extension', link: '/handycontrol/persianToolkit/updatableMarkupExtension/index' },
    ]
    },
    {
    text: 'Quick_start', collapsed: true, items: [
        { text: 'Quick start', link: '/handycontrol/quick_start/index' },
    ]
    },
    {
    text: 'Theme', collapsed: true, items: [
        { text: 'ColorPresetResources', link: '/handycontrol/theme/colorPreset/index' },
        { text: 'Theme', link: '/handycontrol/theme/handyControl' },
        { text: 'Theme', link: '/handycontrol/theme/index' },
    ]
    },
    {
    text: 'Tnx', collapsed: true, items: [
        { text: 'Thanks', link: '/handycontrol/tnx/index' },
    ]
    },
    {
    text: 'Tools', collapsed: true, items: [
        { text: 'Extension', link: '/handycontrol/tools/Extension/index' },
        { text: 'Helper', link: '/handycontrol/tools/Helper/index' },
        { text: 'P/Invoke', link: '/handycontrol/tools/PInvoke/index' },
        { text: 'Tools', link: '/handycontrol/tools/index' },
        { text: 'Validation Rule', link: '/handycontrol/tools/ValidationRule/index' },
    ]
    },
]
},
]